### ISSUE TITLE
Add CSS styles for code snippets

### ISSUE THREAD

**Issue by groovytron** [groovytron/generator-skjol#37]
The following snippets makes the code snippets scrollable in reveal.js slides:

```css
/* styles.css */
.reveal pre.sourceCode {
  overflow-y: scroll;
}
```
